listen_address: :8080

api:
  domain: http://localhost:8080
  signing_secret: "your-super-secret"

app:

database:
  mongodb:
    connection_uri: mongodb://localhost:27017
    database_name: go-vue-starter

mail:
  identity:
  username:
  password:
  host:
  addr:
  from:

  html: true

  subjects:
    welcome: "Welcome to the Go + Vue Starter"
    reset-password: "Reset password request"
    email-verification: "Verify your email address"
    email-changed: "Your email address has been changed"
